{% set name = "CoolProp" %}
{% set version = "6.2.0" %}
{% set sha256 = "55d4693c4bab911ac086d11366d8b42550ccb718e09eecf9adf1937c125bf066" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - matplotlib

test:
  imports:
    - CoolProp
    - CoolProp.tests
    - CoolProp.Plots
    - CoolProp.GUI

about:
  home: https://github.com/CoolProp/CoolProp
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Open-source thermodynamic and transport properties database'

  description: |
    Open-source thermodynamic and transport properties database
  doc_url: http://www.coolprop.org/
  dev_url: https://github.com/CoolProp/CoolProp

extra:
  recipe-maintainers:
    - danilomendesdias
