travis:
  secure:
    BINSTAR_TOKEN: if1fxKvytsXdj3M10xfSpeOi89WELUoz+QNA9oAOBov88RSpt0dRkLmrP793q1XBg5H3nKYnK7D+l0enszgatk65KERT0hTiKmB33eyuUi1P/b6cU/v/EXKiLz65yGaPr0wvh5jlhlS9Z5ii3ARI+O/KrvtSzZ5etI/EnsHx7wVRsmvcaQGFgUPsYTfjTK/Cc0GwMn7zj/uA7afzL+s6HFJPJRFj03pDfr1ozPlpAEiYn/w13EiQkOxzxBleTWZd16cUmPDB/KYGCTBdeAMq67xn1wEYeu7s8o/QLTn68VAp+PW0lAYVQ+5QF0caUauijKOP64sY8vwdgCO0/2gvFcvGXCJjwP+//mm/kQet0NPYb/NkCFEJvB+Bvm2+zYrWG1y5hYtX8aQGBf1ifQoMYaTkGkLWKSgfoDC7RjQg8HZ3b1t0LyqUCz+8iz5p2i2OmP0fh942FdpPKurnNwYgHs6FChwI0wWf+KZlSyYRtNiPIYUOqLN7Sz44szRqSjWAKcNxxPDb+hidw7MS82EX1FtHYtgnqR7cFPzp3+CbD7wct6j4XKyrUKYn+uqujH2R+3ma0kCVy7BYQjgQP1/1hMYgJQX5d/uqOPvRPW7VjLmQapCDATYVmWD0+dWvlOr2T1ONXHtPerkS6vV5PQG/6oK3BVtckojsCRxBqJ3Fkhk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
